### ISSUE TITLE
Icon Requests: Flexget, Postman, AirRadar, Archiver, CleanMyMac, Colloquy, Couleurs, CrossOver, DaisyDisk, Encrypto, ImageOptim, Parallels, Seafile, XMind, VPN Unlimited

### ISSUE THREAD

**Issue by danielsatanik** [wjramos/circl.icns#4]
Hi,
I requested the icon set on tinalatif, I like your designs and hope you won't get mad if I request some additional icons which are currently not on tinalatif.
But first I wait until you created all the icons until the full set of the square flat icons.

Thx in advance

**Comment by wjramos** [comment]
Hey @danielsatanik, I'll take a look through these and try to come up some ideas, for both icon sets.

I'll be making a new branch for icons which will be the same as `master` plus icons not yet merged into the original set.

I am still pretty far away from converting the original set, in the icons I've done so far they've been completely overhauled and cleaned up.

**Comment by danielsatanik** [comment]
Pretty cool. I look forward to the finish.
